version: '3.3'

services:
    registry:
        image: registry:2
        container_name: registry-docker
        restart: always
        environment:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
            REGISTRY_STORAGE_MAINTENANCE: |-
                uploadpurging:
                    enabled: true
                    age: 168h
                    interval: 24h
                    dryrun: false
        volumes:
            - ./storage/registry:/data
        networks:
            - docker-registry

    nginx:
        build:
            context: ./nginx
        container_name: registry-nginx
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./auth:/auth
        networks:
            - docker-registry

networks:
    docker-registry:
        name: docker-registry
        driver: bridge
